"""initial auditable schema

Revision ID: 0bdff5595b23
Revises: 
Create Date: 2026-08-24 15:41:31.942975
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bdff5595b23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_bindings',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('household_id', sa.String(length=100), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index(op.f('ix_device_bindings_household_id'), 'device_bindings', ['household_id'], unique=False)
    op.create_table('households',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbox_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_next_attempt_at'), 'outbox_events', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_topic'), 'outbox_events', ['topic'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_session_id', sa.String(length=100), nullable=False),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('household_id', sa.String(length=100), nullable=False),
    sa.Column('firmware_version', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('clock_status', sa.String(length=30), nullable=False),
    sa.Column('clock_offset_ms', sa.Integer(), nullable=True),
    sa.Column('presence_state', sa.String(length=30), nullable=False),
    sa.Column('collection_state', sa.String(length=30), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('quality', sa.JSON(), nullable=False),
    sa.Column('member_candidates', sa.JSON(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'external_session_id', name='uq_device_session')
    )
    op.create_index(op.f('ix_sessions_correlation_id'), 'sessions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_sessions_device_id'), 'sessions', ['device_id'], unique=False)
    op.create_index(op.f('ix_sessions_household_id'), 'sessions', ['household_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_credentials',
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('api_key_hash')
    )
    op.create_index(op.f('ix_api_credentials_user_id'), 'api_credentials', ['user_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reliable', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_active'), 'assessments', ['active'], unique=False)
    op.create_index(op.f('ix_assessments_session_id'), 'assessments', ['session_id'], unique=False)
    op.create_table('household_members',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('household_id', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('linked_user_id', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_household_members_household_id'), 'household_members', ['household_id'], unique=False)
    op.create_table('household_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_household_user')
    )
    op.create_index(op.f('ix_household_memberships_household_id'), 'household_memberships', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_memberships_user_id'), 'household_memberships', ['user_id'], unique=False)
    op.create_table('member_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('assignment_status', sa.String(length=30), nullable=False),
    sa.Column('member_id', sa.String(length=100), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('claim_method', sa.String(length=30), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_assignments_assignment_status'), 'member_assignments', ['assignment_status'], unique=False)
    op.create_index(op.f('ix_member_assignments_session_id'), 'member_assignments', ['session_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('missing_reason', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'dimension', name='uq_session_dimension')
    )
    op.create_index(op.f('ix_observations_session_id'), 'observations', ['session_id'], unique=False)
    op.create_table('family_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.String(length=100), nullable=False),
    sa.Column('subject_member_id', sa.String(length=100), nullable=False),
    sa.Column('viewer_user_id', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('redline_notifications', sa.Boolean(), nullable=False),
    sa.Column('granted_by_user_id', sa.String(length=100), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['subject_member_id'], ['household_members.id'], ),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'subject_member_id', 'viewer_user_id', 'version', name='uq_grant_version')
    )
    op.create_index(op.f('ix_family_grants_active'), 'family_grants', ['active'], unique=False)
    op.create_index(op.f('ix_family_grants_household_id'), 'family_grants', ['household_id'], unique=False)
    op.create_index(op.f('ix_family_grants_status'), 'family_grants', ['status'], unique=False)
    op.create_index(op.f('ix_family_grants_subject_member_id'), 'family_grants', ['subject_member_id'], unique=False)
    op.create_index(op.f('ix_family_grants_viewer_user_id'), 'family_grants', ['viewer_user_id'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('subject_member_id', sa.String(length=100), nullable=True),
    sa.Column('grant_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('recipient_id', sa.String(length=100), nullable=True),
    sa.Column('authorization_basis', sa.String(length=200), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('input_summary', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grant_id'], ['family_grants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['subject_member_id'], ['household_members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_agent_actions_status'), 'agent_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_actions_status'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_family_grants_viewer_user_id'), table_name='family_grants')
    op.drop_index(op.f('ix_family_grants_subject_member_id'), table_name='family_grants')
    op.drop_index(op.f('ix_family_grants_status'), table_name='family_grants')
    op.drop_index(op.f('ix_family_grants_household_id'), table_name='family_grants')
    op.drop_index(op.f('ix_family_grants_active'), table_name='family_grants')
    op.drop_table('family_grants')
    op.drop_index(op.f('ix_observations_session_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_member_assignments_session_id'), table_name='member_assignments')
    op.drop_index(op.f('ix_member_assignments_assignment_status'), table_name='member_assignments')
    op.drop_table('member_assignments')
    op.drop_index(op.f('ix_household_memberships_user_id'), table_name='household_memberships')
    op.drop_index(op.f('ix_household_memberships_household_id'), table_name='household_memberships')
    op.drop_table('household_memberships')
    op.drop_index(op.f('ix_household_members_household_id'), table_name='household_members')
    op.drop_table('household_members')
    op.drop_index(op.f('ix_assessments_session_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_active'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_api_credentials_user_id'), table_name='api_credentials')
    op.drop_table('api_credentials')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_household_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_device_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_correlation_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_outbox_events_topic'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_next_attempt_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('households')
    op.drop_index(op.f('ix_device_bindings_household_id'), table_name='device_bindings')
    op.drop_table('device_bindings')
    # ### end Alembic commands ###


